### ISSUE TITLE
Internal user guide for shipment creation page

### ISSUE THREAD

**Issue by LauraLangdon** [distributeaid/documentation#11]
## What are we doing?

Officially, we're creating a guide that will be used by new members of the logistics team when they're learning how to use DistroForce. Currently this knowledge is passed in conversation during in-person onboarding of new folks, and most of the work we'll do here is to get that info written down.

But something that happens during documentation (pretty much universally, not just in this case!) is we uncover areas that aren't fully understood by existing users or maybe even have bugs. Part of our job is to *actively* look for these by imagining new logisticians and considering what questions they could have while creating a shipment for the first time.

In particular, any time we think something is self-explanatory, an alert should go off in our brains and we need to ask ourselves if it would be self-explanatory for *everyone*. Sometimes the answer is yes! But we should always, always interrogate that assumption.

## Rough descriptions of tasks

In this issue we'll brain dump tasks, then create smaller issues for each task and assign them. We can edit this as we go along! These seems like the main categories into which each task will fall:

- [ ] Step-by-step "First click this, then do this" sort of instructions
- [ ] Definitions for most fields/menu items: Issue #12
- [ ] Questions for Elliot about how DistroForce works
- [ ] Questions for Basil about how the Google Drive side of things

## Reference materials

- [Meeting with David from logistics to see how they use DistroForce](https://us06web.zoom.us/rec/share/prP84b9mllCCdFSjyyfwbzjhVqlRhWvbYUfWqD-9J_8Jzoh2PKMJNG7xNHiawYG9.Au0gyys3h_0AHuX6)
- [Walkthrough with Elliot](https://us06web.zoom.us/rec/share/iloL3sHJwJFwDcG7tJMfatLfIxFu_SjAE5Mu-_ylcWOn20JcXeokyqj0fBzEI9Qp.cFZK668xvkYZzVTk?startTime=1709579219000)

**Comment by hey-august** [comment]
Test reply

**Comment by LauraLangdon** [comment]
Since we'll be focusing on open source docs work under the new DA tech structure and won't continue working on DistroForce, I'm closing this issue.
