### ISSUE TITLE
INCLUDE MISSION STATEMENT

### ISSUE THREAD

**Issue by oyedeletemitope** [distributeaid/documentation#2]
The README should contain the mission statement for distribute aid.

**Comment by LauraLangdon** [comment]
I'll add these lines, and then you all can add your names below the second bullet point:

- This repo is for collaborating on both internal and external documentation for Distribute Aid
- This repo is maintained by the 2024 docs cohort for Open Source Explorers:

**Comment by LauraLangdon** [comment]
Closed by #10, #9, #5, and #4 🥳
